my_blog/article/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<id>/', views.article_detail, name='article_detail'),
    # 删除文章
    path('article-delete/<id>/', views.article_delete, name='article_delete'),
    # 更新文章
    path('article-update/<id>/', views.article_update, name='article_update'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('question/', include('question.urls', namespace='question')),
]

my_blog/question/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'question'

urlpatterns = [
    path('question-list/', views.question_list, name='question_list'),
    path('question-detail/<id>/', views.question_detail, name='question_detail'),
    # 删除文章
    path('question-delete/<id>/', views.question_delete, name='question_delete'),
    # 更新文章
    path('question-update/<id>/', views.question_update, name='question_update'),
]

my_blog/question/models.py
from django.db import models

# Create your models here.

my_blog/question/views.py
from django.shortcuts import render,redirect
from elasticsearch import Elasticsearch
import time
import re
#client = Elasticsearch(hosts=["127.0.0.1:9200"])
client = Elasticsearch(hosts=["http://kouxun.lenovoresearch2019.cn:9200"])
sub_id = 0


def question_list(request):
    search = request.GET.get('search')
    source = request.GET.get('source')
    page = request.GET.get('page')
    web_source = request.GET.get('web_source')
    if page:
        page = int(page)
    else:
        page = 1
    question_list = client.search(
        index="subject",
        body={
            "query": {
                "match_all": {}
            },
            "from": (page - 1) * 10,
            "size": 10,
        }
    )
    # 搜索查询集
    if search and search != 'None':
        question_list = client.search(
            index="subject",
            body={
                "query": {
                    "multi_match": {
                        "query": search,
                        "fields": ["title", "content", "tag"]
                    }
                },
                "from": (page - 1) * 10,
                "size": 10,
            }
        )
    else:
        # 将 search 参数重置为空
        search = ''
    # 来源查询集
    if source and source != 'None':
        question_list = client.search(
            index="subject",
            body={
                "query": {
                    "multi_match": {
                        "query": source,
                        "fields": ["source"]
                    }
                },
                "from": (page - 1) * 10,
                "size": 10,
            }
        )

    # 网站来源查询集
    if web_source and web_source != 'None':
        question_list = client.search(
            index="subject",
            body={
                "query": {
                    "multi_match": {
                        "query": web_source,
                        "fields": ["web_source"]
                    }
                },
                "from": (page - 1) * 10,
                "size": 10,
            }
        )
    questions = []
    for hit in question_list["hits"]["hits"]:
        hit_dict = {}
        hit_dict["title"] = hit["_source"]["title"]
        content = ""
        for temp in hit["_source"]["contents"]:
            content += temp
        hit_dict["contents"] = content
        hit_dict["tag"] = hit["_source"]["tag"]
        hit_dict["id"] = hit["_id"]
        hit_dict["create_date"] = re.search(r"(\d{4}-\d{1,2}-\d{1,2})", hit["_source"]["create_date"]).group(0)
        hit_dict["source"] = hit["_source"]["source"]
        questions.append(hit_dict)

    total_nums = question_list["hits"]["total"]
    if (page % 10) > 0:
        page_nums = int(total_nums / 10) + 1
    else:
        page_nums = int(total_nums / 10)
    if page != 1:
        has_previous = True
    else:
        has_previous = False
    if page == 1:
        previous_page_number = 1
    else:
        previous_page_number = page - 1
    number = page
    if page != page_nums:
        has_next = True
    else:
        has_next = False
    if page == page_nums:
        next_page_number = 1
    else:
        next_page_number = page + 1
    context = {
        'questions': questions,
        'search': search,
        'has_previous': has_previous,
        'previous_page_number': previous_page_number,
        'number': number,
        'has_next': has_next,
        'next_page_number': next_page_number,
        'page_nums': page_nums,
        'source': source,
        'web_source': web_source,
    }
    return render(request, 'question/question-list.html', context)


def question_detail(request, id):
    question_list = client.search(
        index="subject",
        body={
            "query": {
                "multi_match": {
                    "query": id,
                    "fields": ["_id"]
                }
            }
        }
    )
    hit_dict = {}
    for hit in question_list["hits"]["hits"]:
        hit_dict["title"] = hit["_source"]["title"]
        hit_dict["contents"] = hit["_source"]["contents"]
        hit_dict["tag"] = hit["_source"]["tag"]
        hit_dict["url_object_id"] = hit["_source"]["url_object_id"]
        hit_dict["id"] = hit["_id"]
    context = {'question': hit_dict}
    return render(request, 'question/detail.html', context)


def question_delete(request, id):
    client.delete(index='subject', doc_type='sub_type', id=id)
    time.sleep(1)
    return redirect("question:question_list")


def question_update(request, id):
    # 获取需要修改的具体文章对象
    all_question = client.search(
        index="subject",
        body={
            "query": {
                "multi_match": {
                    "query": id,
                    "fields": ["_id"]
                }
            }
        }
    )
    question = {}
    url_object_id, url, source, tag, temp_id, web_source = "", "", "", "", "",""
    for hit in all_question["hits"]["hits"]:
        create_date = re.search(r"(\d{4}-\d{1,2}-\d{1,2})", hit["_source"]["create_date"]).group(0)
        url = hit["_source"]["url"]
        temp_id = hit["_id"]
        source = hit["_source"]["source"]
        tag = hit["_source"]["tag"]
        web_source = hit["_source"]["web_source"]
        url_object_id = hit["_source"]["url_object_id"]
        question["title"] = hit["_source"]["title"]
        question["contents"] = hit["_source"]["contents"]

    # 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        content_list1 = request.POST['content'].split("\n")
        content_list2 = []
        for content_temp in content_list1:
            if len(content_temp.strip()):
                content_list2.append(content_temp.strip())
        body = {
            "title": request.POST['title'],
            "contents": content_list2,
            "create_date": create_date,
            "url": url,
            "source": source,
            "tag": tag,
            "url_object_id": url_object_id,
            "web_source": web_source,
        }
        client.index(index='subject', doc_type='sub_type', id=temp_id, body=body)
        time.sleep(1)
        return redirect("question:question_detail", id=id)
    else:
        context = {'question': question}
        return render(request, 'question/update.html', context)

my_blog/templates/question/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-12 alert alert-success">
            <a href="#" onclick="confirm_delete()">删除文章</a>
            · <a href="{% url "question:question_update" question.id %}">编辑文章</a>
        </div>
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ question.title }}</h1>
        <div class="col-12 alert alert-success">标题：{{ question.tag }}</div>
        <!-- 文章正文 -->
        <div class="col-12">
            {% for paragraph in question.contents %}
                <p>{{ paragraph }}
                </p>
            {% endfor %}
            <a href="{% url "article:article_detail" question.url_object_id %}">原文链接</a>
        </div>
    </div>
</div>
<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "question:question_delete" question.id %}'
            },
        })
    }
</script>
{% endblock content %}
</body>
</html>

my_blog/templates/question/question-list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'question:question_list' %}?web_source=chinadaily">
                    ChinaDaily
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'question:question_list' %}?web_source=51english">
                    51english
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'question:question_list' %}?web_source=chinaplus">
                    ChinaPlus
                </a>
            </li>
        </ol>
    </nav>
    <!-- 新增，搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text"
                    class="form-control mb-2 mr-sm-2"
                    name="search"
                    placeholder="搜索题目..."
                    required
                >
            </form>
        </div>
    </div>
    <!-- 新增，搜索提示语 -->
    {% if search %}
        {% if questions %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
    {% endif %}
    <div class="row mt-2">
        {% for question in questions %}
            <!-- 文章内容 -->
            <div class="col">

                <!-- 标题 -->
                <h4>
                    <b>
                        <a href="{% url 'question:question_detail' question.id %}"
                           style="color: black;"
                        >
                            {% autoescape off %}{{ question.title }}{% endautoescape %}
                        </a>
                    </b>
                </h4>
                <!-- 摘要 -->
                <div>
                    <p style="color: gray;">
                        {% autoescape off %}{{ question.contents|slice:'400' }}{% endautoescape %}...
                    </p>
                </div>
                <!-- 注脚 -->
                <p>
                    <!-- 附加信息 -->
                    <span>
                        <i class="fas fa-clock" style="color: pink;"></i>
                        {{ question.create_date }}
                    </span>
                </p>
            </div>
            <hr style="width: 100%;"/>
        {% endfor %}
    </div>
    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if has_previous %}
                    <a href="?page=1&search={{ search }}&source={{ source }}&tag={{ tag }}&web_source={{ web_source }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ previous_page_number }}&search={{ search }}&source={{ source }}&tag={{ tag }}&web_source={{ web_source }}"
                       class="btn btn-secondary"
                    >
                        {{ previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if has_next %}
                    <a href="?page={{ next_page_number }}&search={{ search }}&source={{ source }}&tag={{ tag }}&web_source={{ web_source }}"
                       class="btn btn-secondary"
                    >
                        {{ next_page_number }}</a>
                    <span>...</span>
                    <a href="?page={{ page_nums }}&search={{ search }}&source={{ source }}&tag={{ tag }}&web_source={{ web_source }}"
                       class="btn btn-success"
                    >
                        {{ page_nums }} &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>

</div>
{% endblock content %}

my_blog/templates/question/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ question.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="content" name="content" rows="20">{% for i in question.contents %}        {{ i }}
{% endfor %}
                    </textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}