my_blog/article/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<id>/', views.article_detail, name='article_detail'),
    # 删除文章
    path('article-delete/<id>/', views.article_delete, name='article_delete'),
    # 更新文章
    path('article-update/<id>/', views.article_update, name='article_update'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('question/', include('question.urls', namespace='question')),
]

my_blog/article/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.utils import timezone

class ArticlePost(models.Model):
    title = models.CharField(max_length=100)
    create_date = models.DateTimeField(default=timezone.now)
    url = models.CharField(max_length=100)
    url_object_id = models.CharField(max_length=100)
    source = models.CharField(max_length=100)
    tag = models.CharField(max_length=100)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-create_date',)

    def __str__(self):
        return self.title

my_blog/article/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import ArticlePost


# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'content','tag')

my_blog/article/views.py
from django.shortcuts import render, redirect
from elasticsearch import Elasticsearch
import time
import re

#client = Elasticsearch(hosts=["127.0.0.1:9200"])
client = Elasticsearch(hosts=["http://kouxun.lenovoresearch2019.cn:9200"])


def article_list(request):
    search = request.GET.get('search')
    source = request.GET.get('source')
    tags = request.GET.get('tag')
    page = request.GET.get('page')
    web_source = request.GET.get('web_source')
    if page:
        page = int(page)
    else:
        page = 1
    article_list = client.search(
        index="super_material",
        body={
            "query": {
                "match_all": {}
            },
            "from": (page - 1) * 10,
            "size": 10,
            "sort": "score"
        }
    )
    # 搜索查询集
    if search and search != 'None':
        article_list = client.search(
            index="super_material",
            body={
                "query": {
                    "multi_match": {
                        "query": search,
                        "fields": ["title", "content", "tag"]
                    }
                },
                "from": (page - 1) * 10,
                "size": 10,
                "sort": "score"
            }
        )
    else:
        # 将 search 参数重置为空
        search = ''
    # 来源查询集
    if source and source != 'None':
        article_list = client.search(
            index="super_material",
            body={
                "query": {
                    "multi_match": {
                        "query": source,
                        "fields": ["source"]
                    }
                },
                "from": (page - 1) * 10,
                "size": 10,
                "sort": "score"
            }
        )

        # 标签查询集
    if tags and tags != 'None':
        article_list = client.search(
            index="super_material",
            body={
                "query": {
                    "multi_match": {
                        "query": tags,
                        "fields": ["tag"]
                    }
                },
                "from": (page - 1) * 10,
                "size": 10,
                "sort": "score"
            }
        )
    # 网站来源查询集
    if web_source and web_source != 'None':
        article_list = client.search(
            index="super_material",
            body={
                "query": {
                    "multi_match": {
                        "query": web_source,
                        "fields": ["web_source"]
                    }
                },
                "from": (page - 1) * 10,
                "size": 10,
                "sort": "score"
            }
        )
    articles = []
    for hit in article_list["hits"]["hits"]:
        hit_dict = {}
        hit_dict["title"] = hit["_source"]["title"]
        contents = hit["_source"]["content"]
        hit_dict["content"] = contents.replace('###', '')
        hit_dict["tag"] = hit["_source"]["tag"]
        hit_dict["id"] = hit["_source"]["url_object_id"]
        hit_dict["create_date"] = re.search(r"(\d{4}-\d{1,2}-\d{1,2})", hit["_source"]["create_date"]).group(0)
        hit_dict["source"] = hit["_source"]["source"]
        articles.append(hit_dict)

    total_nums = article_list["hits"]["total"]
    if (page % 10) > 0:
        page_nums = int(total_nums / 10) + 1
    else:
        page_nums = int(total_nums / 10)
    if page != 1:
        has_previous = True
    else:
        has_previous = False
    if page == 1:
        previous_page_number = 1
    else:
        previous_page_number = page - 1
    number = page
    if page != page_nums:
        has_next = True
    else:
        has_next = False
    if page == page_nums:
        next_page_number = 1
    else:
        next_page_number = page + 1
    context = {
        'articles': articles,
        'search': search,
        'has_previous': has_previous,
        'previous_page_number': previous_page_number,
        'number': number,
        'has_next': has_next,
        'next_page_number': next_page_number,
        'page_nums': page_nums,
        'tag': tags,
        'source': source,
        'web_source': web_source,
    }
    return render(request, 'article/list.html', context)


def article_detail(request, id):
    all_article = client.search(
        index="super_material",
        body={
            "query": {
                "multi_match": {
                    "query": id,
                    "fields": ["url_object_id"]
                }
            }
        }
    )
    hit_dict = {}
    for hit in all_article["hits"]["hits"]:
        hit_dict["title"] = hit["_source"]["title"]
        contents = hit["_source"]["content"].strip()
        content_list = contents.split("###")
        word_normal = []
        for i in content_list:
            j = i.split(" ")
            word_normal.append(j)
        hit_dict["content"] = word_normal
        hit_dict["tag"] = hit["_source"]["tag"]
        hit_dict["id"] = hit["_source"]["url_object_id"]
        hit_dict["web_source"] = hit["_source"]["web_source"]
        superClasswords = []
        for word in hit["_source"]["superclassWord"]:
            superClasswords.append(word)
            superClasswords.append(word.title())
            superClasswords.append(word.upper())
        hit_dict["superclassWord"] = superClasswords
    context = {'articles': hit_dict}
    return render(request, 'article/detail.html', context)


def article_delete(request, id):
    client.delete(index='super_material', doc_type='mate_type', id=id)
    time.sleep(1)
    return redirect("article:article_list")


def article_update(request, id):
    # 获取需要修改的具体文章对象
    all_article = client.search(
        index="super_material",
        body={
            "query": {
                "multi_match": {
                    "query": id,
                    "fields": ["url_object_id"]
                }
            }
        }
    )
    article = {}
    url_object_id, url, source, tag, web_source = "", "", "", "", ""
    for hit in all_article["hits"]["hits"]:
        create_date = re.search(r"(\d{4}-\d{1,2}-\d{1,2})", hit["_source"]["create_date"]).group(0)
        url = hit["_source"]["url"]
        source = hit["_source"]["source"]
        tag = hit["_source"]["tag"]
        web_source = hit["_source"]["web_source"]
        url_object_id = hit["_source"]["url_object_id"]
        article["title"] = hit["_source"]["title"]
        temp = hit["_source"]["content"].strip()
        contents = []
        for content in temp.split("###"):
            if content != ' 'and len(content) != 0:
                contents.append(content)
        article["content"] = contents
    # all_question = client.search(
    #     index="subject",
    #     body={
    #         "query": {
    #             "multi_match": {
    #                 "query": id,
    #                 "fields": ["url_object_id"]
    #             }
    #         }
    #     }
    # )
    # question_ids = []
    # for question_id in all_question["hits"]["hits"]:
    #     question_ids.append(question_id["_id"])
    if request.method == "POST":
        content_list1 = request.POST['content'].split("\n")
        content_list2 = []
        for content_temp in content_list1:
            if len(content_temp.strip()):
                content_list2.append(content_temp.strip())
        body = {
            "title": request.POST['title'],
            "contents": content_list2,
            "create_date": create_date,
            "url": url,
            "source": source,
            "tag": tag,
            "url_object_id": url_object_id,
            "web_source": web_source,
        }
        client.index(index='subject', doc_type='sub_type', body=body)
        time.sleep(1)
        return redirect("article:article_detail", id=id)
    else:
        context = {'article': article}
        return render(request, 'article/update.html', context)

my_blog/templates/article/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-12 alert alert-success">
            <a href="#" onclick="confirm_delete()">删除文章</a>
            · <a href="{% url "article:article_update" articles.id %}">编辑文章</a>
        </div>
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ articles.title }}</h1>
        <div class="col-12 alert alert-success">标题：{{ articles.tag }}</div>
        <!-- 文章正文 -->
        <div class="col-12">
            {% for paragraph in articles.content %}
                <p>
                    {% for word in paragraph %}
                        {% if word in articles.superclassWord %}
                            <span style="color:#F00">{{ word }}</span>
                        {% else %}
                            <span>{{ word }}</span>
                        {% endif %}
                    {% endfor %}
                </p>
            {% endfor %}
        </div>
    </div>
</div>
<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "article:article_delete" articles.id %}'
            },
        })
    }
</script>
{% endblock content %}
</body>
</html>

my_blog/templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?web_source=chinadaily">
                    ChinaDaily
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?web_source=51english">
                    51english
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?web_source=chinaplus">
                    ChinaPlus
                </a>
            </li>
        </ol>
    </nav>
    <!-- 新增，搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text"
                    class="form-control mb-2 mr-sm-2"
                    name="search"
                    placeholder="搜索文章..."
                    required
                >
            </form>
        </div>
    </div>
    <!-- 新增，搜索提示语 -->
    {% if search %}
        {% if articles %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
    {% endif %}
    <div class="row mt-2">
        {% for article in articles %}
            <!-- 文章内容 -->
            <div class="col">
                <!-- tag -->
                {% if article.tag %}
                    <a  role="button"
                        href="{% url 'article:article_list' %}?tag={{ article.tag }}"
                        class="btn btn-sm mb-2 btn-warning"
                    >
                        {{ article.tag }}
                    </a>
                {% endif %}
                <!-- source -->
                <span>
                        <a href="{% url 'article:article_list' %}?source={{ article.source }}"
                           class="badge badge-secondary"
                        >
                            {{ article.source }}
                        </a>
                </span>

                <!-- 标题 -->
                <h4>
                    <b>
                        <a href="{% url 'article:article_detail' article.id %}"
                           style="color: black;"
                        >
                            {% autoescape off %}{{ article.title }}{% endautoescape %}
                        </a>
                    </b>
                </h4>
                <!-- 摘要 -->
                <div>
                    <p style="color: gray;">
                        {% autoescape off %}{{ article.content|slice:'400' }}{% endautoescape %}...
                    </p>
                </div>
                <!-- 注脚 -->
                <p>
                    <span>
                        <i class="fas fa-clock" style="color: pink;"></i>
                        {{ article.create_date }}
                    </span>
                </p>
            </div>
            <hr style="width: 100%;"/>
        {% endfor %}
    </div>
    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if has_previous %}
                    <a href="?page=1&search={{ search }}&source={{ source }}&tag={{ tag }}&web_source={{ web_source }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ previous_page_number }}&search={{ search }}&source={{ source }}&tag={{ tag }}&web_source={{ web_source }}"
                       class="btn btn-secondary"
                    >
                        {{ previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if has_next %}
                    <a href="?page={{ next_page_number }}&search={{ search }}&source={{ source }}&tag={{ tag }}&web_source={{ web_source }}"
                       class="btn btn-secondary"
                    >
                        {{ next_page_number }}</a>
                    <span>...</span>
                    <a href="?page={{ page_nums }}&search={{ search }}&source={{ source }}&tag={{ tag }}&web_source={{ web_source }}"
                       class="btn btn-success"
                    >
                        {{ page_nums }} &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>

</div>
{% endblock content %}

my_blog/templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <textarea  type="text" class="form-control" id="content" name="content" rows="20">{% for i in article.content %}        {{ i }}
{% endfor %}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}