my_blog/article/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<id>/', views.article_detail, name='article_detail'),
    # 删除文章
    path('article-delete/<id>/', views.article_delete, name='article_delete'),
    # 更新文章
    path('article-update/<id>/', views.article_update, name='article_update'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('question/', include('question.urls', namespace='question')),
]

my_blog/question/urls.py
from django.urls import path
from . import views
# 正在部署的应用的名称
app_name = 'question'

urlpatterns = [
    path('question-list/', views.question_list, name='question_list'),
    path('question-detail/<id>/', views.question_detail, name='question_detail'),
    # 删除文章
    path('question-delete/<id>/', views.question_delete, name='question_delete'),
    # 更新文章
    path('question-update/<id>/', views.question_update, name='question_update'),
]

my_blog/templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title  %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- 引入layer.js -->
    <script src="{% static 'layer/layer.js' %}"></script>
</body>

</html>

my_blog/templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright &copy; www.lenovo.com.cn  2019</h5>
    </div>
</footer>

my_blog/templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="{% url 'article:article_list' %}">素材文章列表</a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- 条目 -->
        <li class="nav-item">
          <a class="navbar-brand" href="{% url 'question:question_list' %}">题目文章列表</a>
        </li>
      </ul>
    </div>

  </div>
</nav>